export { default as Splash } from './Splash'
export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as CoreCapability } from './CoreCapability' 
export { default as CoreIndustry } from './CoreIndustry'
export { default as CompleteProfile } from './CompleteProfile'
export { default as HomeScreen } from './HomeScreen'
export { default as Comment } from './Comment'
export { default as Profile } from './Profile'
export { default as AboutUs } from './AboutUs'
export { default as TermCondition } from './TermCondition'
export { default as ChangePassword } from './ChangePassword'
export { default as ApplicantsDetails } from './ApplicantsDetails'
export { default as MessageScreen } from './MessageScreen'
export { default as Messages} from './Messages'