export {default as Home} from './Home'
export {default as Community} from './Community'
export {default as PostPage} from './PostPage'
export {default as Notifications} from './Notifications'
export {default as Chats} from './Chats'